In [1]:
# пока n<10 прибавить к n единицу и распечатать значение:
n = 0
while n < 10
    n += 1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [2]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]
i = 1
while i <= length(myfriends)
    friend = myfriends[i]
    println("Hi $friend, it's great to see you!")
    i += 1
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [3]:
for n in 1:2:10
    println(n)
end

1
3
5
7
9


In [4]:
for n in 1:1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [5]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]
for friend in myfriends
    println("Hi $friend, it's great to see you!")
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [6]:
# инициализация массива m x n из нулей:
m, n = 5, 5
A = fill(0, (m, n))
# формирование массива, в котором значение каждой записи
# является суммой индексов строки и столбца:
for i in 1:m
    for j in 1:n
        A[i, j] = i + j
    end
end
A

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [7]:
# инициализация массива m x n из нулей:
B = fill(0, (m, n))
for i in 1:m, j in 1:n
    B[i, j] = i + j
end
B

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [8]:
C = [i + j for i in 1:m, j in 1:n]
C

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [12]:
# используем `&&` для реализации операции "AND"
# операция % вычисляет остаток от деления
N = 15
if (N % 3 == 0) && (N % 5 == 0)
    println("FizzBuzz")
elseif N % 3 == 0
    println("Fizz")
elseif N % 5 == 0
    println("Buzz")
else
    println(N)
end

FizzBuzz


In [13]:
x = 5
y = 10
(x > y) ? x : y

10

In [14]:
function sayhi(name)
    println("Hi $name, it's great to see you!")
end
# функция возведения в квадрат:
function f(x)
    x^2
end

f (generic function with 1 method)

In [15]:
sayhi("C-3PO")
f(42)

Hi C-3PO, it's great to see you!


1764

In [16]:
sayhi2(name) = println("Hi $name, it's great to see you!")
f2(x) = x^2

f2 (generic function with 1 method)

In [17]:
sayhi2("C-3PO")
f2(42)

Hi C-3PO, it's great to see you!


1764

In [18]:
sayhi3 = name -> println("Hi $name, it's great to see you!")
f3 = x -> x^2

#5 (generic function with 1 method)

In [19]:
sayhi3("C-3PO")
f3(42)

Hi C-3PO, it's great to see you!


1764

In [21]:
# задаём массив v:
v = [3, 5, 2]
sort(v)
v

3-element Vector{Int64}:
 3
 5
 2

In [22]:
sort!(v)
v

3-element Vector{Int64}:
 2
 3
 5

In [23]:
v = [3, 5, 2]
result = sort(v)
result

3-element Vector{Int64}:
 2
 3
 5

In [24]:
map(f, [1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

In [25]:
f(x) = x^2
broadcast(f, [1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

In [26]:
# Задаём матрицу A:
A = [i + 3*j for j in 0:2, i in 1:3]
A

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [27]:
f(A)

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

In [28]:
broadcast(f, A)

3×3 Matrix{Int64}:
  1   4   9
 16  25  36
 49  64  81

In [29]:
A .+ 2 .* f.(A) ./ A

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

In [30]:
broadcast(x -> x + 2 * f(x) / x, A)

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

In [31]:
import Pkg
Pkg.add("Example")

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
   Installed Example ─ v0.5.5
    Updating `~/.julia/environments/v1.11/Project.toml`
  [7876af07] + Example v0.5.5
    Updating `~/.julia/environments/v1.11/Manifest.toml`
  [7876af07] + Example v0.5.5
Precompiling project...
   1217.3 ms  ✓ ConcreteStructs
   1214.5 ms  ✓ IteratorInterfaceExtensions
   2063.4 ms  ✓ SimpleUnPack
   1218.2 ms  ✓ ExprTools
   1223.8 ms  ✓ PositiveFactorizations
   1228.7 ms  ✓ MuladdMacro
   1222.0 ms  ✓ LaTeXStrings
   1226.0 ms  ✓ AbstractFFTs
   1258.1 ms  ✓ FunctionWrappers
    665.7 ms  ✓ Example
    713.6 ms  ✓ Pipe
    895.1 ms  ✓ Contour
    910.5 ms  ✓ StatsAPI
    944.3 ms  ✓ TensorCore
    960.1 ms  ✓ CEnum
    604.8 ms  ✓ UnPack
   1355.8 ms  ✓ ADTypes
    559.8 ms  ✓ CommonSolve
    824.2 ms  ✓ Measures
    873.8 ms  ✓ InverseFunctions
   1017.8 ms  ✓ Statistics
    697.3 ms  ✓ ManualMemory
    737.8 ms  ✓ PoissonRandom
   2553.2 ms  ✓ Format
   200

In [32]:
Pkg.add("Colors")
using Colors

   Resolving package versions...
   Installed Colors ─ v0.13.1
    Updating `~/.julia/environments/v1.11/Project.toml`
  [5ae59095] + Colors v0.13.1
    Updating `~/.julia/environments/v1.11/Manifest.toml`
  [5ae59095] ↑ Colors v0.13.0 ⇒ v0.13.1
Precompiling project...
   4989.9 ms  ✓ Colors
    900.1 ms  ✓ SparseMatrixColorings → SparseMatrixColoringsColorsExt
   3355.4 ms  ✓ ColorSchemes
  10230.0 ms  ✓ PlotUtils
   3303.1 ms  ✓ PlotThemes
   4595.5 ms  ✓ RecipesPipeline
  65153.0 ms  ✓ Plots
   4107.8 ms  ✓ Plots → UnitfulExt
   5634.3 ms  ✓ Plots → IJuliaExt
  9 dependencies successfully precompiled in 95 seconds. 458 already precompiled.


In [33]:
palette = distinguishable_colors(100)

In [34]:
rand(palette, 3, 3)

In [36]:
n = 1
while n <= 100
    println(n, ", ", n^2)
    n += 1
end

1, 1
2, 4
3, 9
4, 16
5, 25
6, 36
7, 49
8, 64
9, 81
10, 100
11, 121
12, 144
13, 169
14, 196
15, 225
16, 256
17, 289
18, 324
19, 361
20, 400
21, 441
22, 484
23, 529
24, 576
25, 625
26, 676
27, 729
28, 784
29, 841
30, 900
31, 961
32, 1024
33, 1089
34, 1156
35, 1225
36, 1296
37, 1369
38, 1444
39, 1521
40, 1600
41, 1681
42, 1764
43, 1849
44, 1936
45, 2025
46, 2116
47, 2209
48, 2304
49, 2401
50, 2500
51, 2601
52, 2704
53, 2809
54, 2916
55, 3025
56, 3136
57, 3249
58, 3364
59, 3481
60, 3600
61, 3721
62, 3844
63, 3969
64, 4096
65, 4225
66, 4356
67, 4489
68, 4624
69, 4761
70, 4900
71, 5041
72, 5184
73, 5329
74, 5476
75, 5625
76, 5776
77, 5929
78, 6084
79, 6241
80, 6400
81, 6561
82, 6724
83, 6889
84, 7056
85, 7225
86, 7396
87, 7569
88, 7744
89, 7921
90, 8100
91, 8281
92, 8464
93, 8649
94, 8836
95, 9025
96, 9216
97, 9409
98, 9604
99, 9801
100, 10000


In [37]:
for n in 1:100
    println(n, ", ", n^2)
end

1, 1
2, 4
3, 9
4, 16
5, 25
6, 36
7, 49
8, 64
9, 81
10, 100
11, 121
12, 144
13, 169
14, 196
15, 225
16, 256
17, 289
18, 324
19, 361
20, 400
21, 441
22, 484
23, 529
24, 576
25, 625
26, 676
27, 729
28, 784
29, 841
30, 900
31, 961
32, 1024
33, 1089
34, 1156
35, 1225
36, 1296
37, 1369
38, 1444
39, 1521
40, 1600
41, 1681
42, 1764
43, 1849
44, 1936
45, 2025
46, 2116
47, 2209
48, 2304
49, 2401
50, 2500
51, 2601
52, 2704
53, 2809
54, 2916
55, 3025
56, 3136
57, 3249
58, 3364
59, 3481
60, 3600
61, 3721
62, 3844
63, 3969
64, 4096
65, 4225
66, 4356
67, 4489
68, 4624
69, 4761
70, 4900
71, 5041
72, 5184
73, 5329
74, 5476
75, 5625
76, 5776
77, 5929
78, 6084
79, 6241
80, 6400
81, 6561
82, 6724
83, 6889
84, 7056
85, 7225
86, 7396
87, 7569
88, 7744
89, 7921
90, 8100
91, 8281
92, 8464
93, 8649
94, 8836
95, 9025
96, 9216
97, 9409
98, 9604
99, 9801
100, 10000


In [38]:
squares = Dict()
for n in 1:100
    squares[n] = n^2
end
println(squares)

Dict{Any, Any}(5 => 25, 56 => 3136, 35 => 1225, 55 => 3025, 60 => 3600, 30 => 900, 32 => 1024, 6 => 36, 67 => 4489, 45 => 2025, 73 => 5329, 64 => 4096, 90 => 8100, 4 => 16, 13 => 169, 54 => 2916, 63 => 3969, 86 => 7396, 91 => 8281, 62 => 3844, 58 => 3364, 52 => 2704, 12 => 144, 28 => 784, 75 => 5625, 23 => 529, 92 => 8464, 41 => 1681, 43 => 1849, 11 => 121, 36 => 1296, 68 => 4624, 69 => 4761, 98 => 9604, 82 => 6724, 85 => 7225, 39 => 1521, 84 => 7056, 77 => 5929, 7 => 49, 25 => 625, 95 => 9025, 71 => 5041, 66 => 4356, 76 => 5776, 34 => 1156, 50 => 2500, 59 => 3481, 93 => 8649, 2 => 4, 10 => 100, 18 => 324, 26 => 676, 27 => 729, 42 => 1764, 87 => 7569, 100 => 10000, 79 => 6241, 16 => 256, 20 => 400, 81 => 6561, 19 => 361, 49 => 2401, 44 => 1936, 9 => 81, 31 => 961, 74 => 5476, 61 => 3721, 29 => 841, 94 => 8836, 46 => 2116, 57 => 3249, 70 => 4900, 21 => 441, 38 => 1444, 88 => 7744, 78 => 6084, 72 => 5184, 24 => 576, 8 => 64, 17 => 289, 37 => 1369, 1 => 1, 53 => 2809, 22 => 484, 47 => 220

In [39]:
squares_arr = [n^2 for n in 1:100]
println(squares_arr)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000]


In [40]:
n = 3
if n % 2 == 0
    println(n)
else 
    println("Нечетное")
end

Нечетное


In [41]:
n = 4 
println(n % 2 == 0 ? n : "Нечетное")

4


In [42]:
function add_one(x)
    return x + 1
end
println(add_one(1))

2


In [43]:
A = [1 2 3; 1 2 3; 1 2 3]
B = map(x -> x + 1, A)
B

3×3 Matrix{Int64}:
 2  3  4
 2  3  4
 2  3  4

In [44]:
A = [1 1 3; 5 2 6; -2 -1 -3]
println(map(x -> x ^ 3, A))

[1 1 27; 125 8 216; -8 -1 -27]


In [45]:
A[:, 3] = A[:, 2] + A[:, 3]
A

3×3 Matrix{Int64}:
  1   1   4
  5   2   8
 -2  -1  -4

In [46]:
B = repeat([10 -10 10], 15, 1)

15×3 Matrix{Int64}:
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10

In [47]:
C = B' * B
C

3×3 Matrix{Int64}:
  1500  -1500   1500
 -1500   1500  -1500
  1500  -1500   1500

In [48]:
Z = zeros(Int, 6, 6)
E = ones(Int, 6, 6)

n = 6
Z1 = copy(Z)
for i in 1:n
    for j in 1:n
        if abs(i - j) == 1
            Z1[i, j] = 1
        end
    end
end
Z1

6×6 Matrix{Int64}:
 0  1  0  0  0  0
 1  0  1  0  0  0
 0  1  0  1  0  0
 0  0  1  0  1  0
 0  0  0  1  0  1
 0  0  0  0  1  0

In [49]:
Z2 = copy(Z)
for i in 1:n
    if i+2 < n
        Z2[i, i] = 1
        Z2[i, i+2] = 1
    elseif (i == 3) || (i == 4)
        Z2[i, i] = 1
        Z2[i, i+2] = 1
        Z2[i, i-2] = 1
    else
        Z2[i, i] = 1
        Z2[i, i-2] = 1
    end
end
Z2

6×6 Matrix{Int64}:
 1  0  1  0  0  0
 0  1  0  1  0  0
 0  0  1  0  1  0
 0  1  0  1  0  1
 0  0  1  0  1  0
 0  0  0  1  0  1

In [51]:
Z3 = copy(Z)
for i in 1:n
    for j in 1:n
        if (i+j) % 2 != 0
            Z3[i, j] = 1
        end
    end
end
Z3

6×6 Matrix{Int64}:
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0

In [52]:
Z4 = copy(Z)
for i in 1:n
    for j in 1:n
        if (i+j) % 2 == 0
            Z4[i, j] = 1
        end
    end
end
Z4

6×6 Matrix{Int64}:
 1  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  1

In [53]:
function outer(x, y, operation)
    return [operation(i, j) for i in x, j in y]
end

outer (generic function with 1 method)

In [54]:
A1 = outer(0:4, 0:4, +)

5×5 Matrix{Int64}:
 0  1  2  3  4
 1  2  3  4  5
 2  3  4  5  6
 3  4  5  6  7
 4  5  6  7  8

In [55]:
A2 = outer(0:4, 1:5, ^)
A2

5×5 Matrix{Int64}:
 0   0   0    0     0
 1   1   1    1     1
 2   4   8   16    32
 3   9  27   81   243
 4  16  64  256  1024

In [56]:
A3 = outer(0:4, 0:4, (x, y) -> mod(x+y, 5))
A3

5×5 Matrix{Int64}:
 0  1  2  3  4
 1  2  3  4  0
 2  3  4  0  1
 3  4  0  1  2
 4  0  1  2  3

In [57]:
A4 = outer(0:9, 0:9, (x, y) -> mod(x+y, 10))
A4

10×10 Matrix{Int64}:
 0  1  2  3  4  5  6  7  8  9
 1  2  3  4  5  6  7  8  9  0
 2  3  4  5  6  7  8  9  0  1
 3  4  5  6  7  8  9  0  1  2
 4  5  6  7  8  9  0  1  2  3
 5  6  7  8  9  0  1  2  3  4
 6  7  8  9  0  1  2  3  4  5
 7  8  9  0  1  2  3  4  5  6
 8  9  0  1  2  3  4  5  6  7
 9  0  1  2  3  4  5  6  7  8

In [58]:
A5 = outer(0:8, 0:8, (x, y) -> mod(x-y, 9))
A5

9×9 Matrix{Int64}:
 0  8  7  6  5  4  3  2  1
 1  0  8  7  6  5  4  3  2
 2  1  0  8  7  6  5  4  3
 3  2  1  0  8  7  6  5  4
 4  3  2  1  0  8  7  6  5
 5  4  3  2  1  0  8  7  6
 6  5  4  3  2  1  0  8  7
 7  6  5  4  3  2  1  0  8
 8  7  6  5  4  3  2  1  0

In [69]:
A = [
    1 2 3 4 5;
    2 1 2 3 4;
    3 2 1 2 3;
    4 3 2 1 2;
    5 4 3 2 1;
]
b = [7; -1; -3; 5; 17]

x = A \ b
x

5-element Vector{Float64}:
 -2.0000000000000036
  3.0000000000000058
  4.999999999999998
  1.9999999999999991
 -3.999999999999999

In [70]:
M = rand(1:10, 6, 10)
M


6×10 Matrix{Int64}:
 8  9   5  1  5   4   2  10  9  2
 8  8   9  5  1   8  10   3  5  1
 2  9   8  1  7  10   8   9  9  9
 5  9  10  2  1   6   4   3  8  4
 9  8   9  6  7   1   7   1  7  4
 7  6   8  8  8   1   7   7  4  8

In [71]:
N = 4
greater_than_N = sum(M .> N)
greater_than_N

41

In [72]:
twice = [i for i=1:6 if sum(M[i, :].==7)==2]
twice

Int64[]

In [73]:
K = 75
pairs = []
for i in 1:size(M, 2)-1
    for j in i + 1:size(M, 2)
        if sum(M[:, i] .+ M[:,j]) > K
            push!(pairs, (i, j))
        end
    end
end
pairs

18-element Vector{Any}:
 (1, 2)
 (1, 3)
 (1, 7)
 (1, 9)
 (2, 3)
 (2, 5)
 (2, 6)
 (2, 7)
 (2, 8)
 (2, 9)
 (2, 10)
 (3, 5)
 (3, 6)
 (3, 7)
 (3, 8)
 (3, 9)
 (3, 10)
 (7, 9)

In [74]:
sum1 = sum(i^4 / (3 + j) for i in 1:20 for j in 1:5)
sum1

639215.2833333334

In [75]:
sum2 = sum(i^4 / (3 + i * j) for i in 1:20 for j in 1:5)

89912.02146097136